DROP TABLE IF EXISTS users;

CREATE TABLE users (
	id serial NOT NULL,
	name VARCHAR(30) NULL DEFAULT NULL,
	age INT NULL DEFAULT NULL,
	email VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (id)
);

select * from users;