server:
   port: 8091

# DataSource Config
spring:
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/push
      username: menghuanwd
      password: password

#  MybatisPlus Config
mybatis-plus:
  type-aliases-package: com.menghuanwd.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto

# Logger Config
logging:
  pattern:
    console: '%p%m%n'
  level:
    root: warn
    com.menghuanwd.dao: trace
